[project]
name = "study-learning-firecrawl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "firecrawl-py>=4.8.0",
    "ipykernel>=7.1.0",
]
